server:
  port: 8080

spring:
  application:
    name: lee-utils

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always


logging:
  level:
    com.lee: debug
    org.springframework.cloud: info
feign:
  logger: full
  level: FULL

openweather:
  api-key: e30b514a95528199c857c8b33d8ed21d
  default-lat: 35.42
  default-lon: 119.52